server:
  port: 8100

spring:
  application:
    name: payment-service
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/payment
    username: ed
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true